spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/store_app
    username: root
    password: rootroot
  flyway:
    baseline-on-migrate: true
app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000

server:
  port: 8090