spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    mvc:
      pathmartch:
        matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/store_app
    username: root
    password: rootroot
  flyway:
    baseline-on-migrate: true